#!/bin/bash
pygettext.py -d astronex -o astronex.pot astronex/*.py astronex/*/*.py
mv astronex.pot ./locale

cd locale

for l in *.po;
do
	msgmerge -U $l astronex.pot ;
    msgfmt.py 
done

exit

for l in *.po;
do
    msgfmt.py $l
    ll=${l%.po}
    mv ${ll}.mo ../astronex/locale/${ll}/LC_MESSAGES/astronex.mo
done
